#!/usr/bin/env bash
# Install nginx on your web-01
# Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx


sudo sed -i -e 's/listen 80 default_server;/listen 80;/g' -e '24i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /var/www/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart;

