#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt-get update
sudo apt-get install -y nginx


sudo sed -i -e 's/listen 80 default_server;/listen 80;/g' -e '24i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' -e '/error_page 404/i\error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html


echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart;
