#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt-get update
sudo apt-get install -y nginx
mkdir /etc/nginx/html

sudo sed -i -e 's/listen 80 default_server;/listen 80;/g' \
-e '24i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' \
-e '/error_page 404/i\error_page 404 /404.html;' \
-e '/server_name _;/a\add_header X-Served-By $hostname;' \
/etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html

sudo service nginx restart;
